CREATE TABLE teaching_periods (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_assignment_id BIGINT    NOT NULL,
    academic_period_id     BIGINT    NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    CONSTRAINT fk_teaching_periods_assignment FOREIGN KEY (teaching_assignment_id) REFERENCES teaching_assignments (id),
    CONSTRAINT fk_teaching_periods_period FOREIGN KEY (academic_period_id) REFERENCES academic_periods (id),
    CONSTRAINT uk_teaching_periods UNIQUE (teaching_assignment_id, academic_period_id)
);
