CREATE TABLE grading_scales (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    minimum_value NUMERIC(6, 2) NOT NULL,
    maximum_value NUMERIC(6, 2) NOT NULL,
    created_at    TIMESTAMP     NOT NULL
);
