-- Importaciones en segundo plano: el POST deja el batch en QUEUED y un worker lo procesa después. import_type y
-- teaching_period_id permiten reanudarlo tras un reinicio (NULL = importación síncrona anterior a esta versión).
-- error_code/error_message explican un FAILED que no es por filas (columnas faltantes, archivo ilegible…).
ALTER TABLE import_batches ADD COLUMN import_type VARCHAR(30);
ALTER TABLE import_batches ADD COLUMN teaching_period_id BIGINT;
ALTER TABLE import_batches ADD COLUMN error_code VARCHAR(100);
ALTER TABLE import_batches ADD COLUMN error_message TEXT;
ALTER TABLE import_batches ADD COLUMN started_at TIMESTAMP;
CREATE INDEX idx_import_batches_status ON import_batches (status);

-- Primeros errores por fila de cada importación (antes solo viajaban en la respuesta del POST); el detalle completo
-- sigue en el reporte de errores en Excel.
CREATE TABLE import_batch_errors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT NOT NULL,
    row_num     INT    NOT NULL,
    column_name VARCHAR(100),
    message     TEXT   NOT NULL,
    CONSTRAINT fk_import_batch_errors_batch FOREIGN KEY (batch_id) REFERENCES import_batches (id) ON DELETE CASCADE
);
CREATE INDEX idx_import_batch_errors_batch ON import_batch_errors (batch_id, id);
