CREATE TABLE grading_configurations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id BIGINT    NOT NULL,
    grading_scale_id   BIGINT    NOT NULL,
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NOT NULL,
    CONSTRAINT fk_grading_configurations_teaching_period FOREIGN KEY (teaching_period_id) REFERENCES teaching_periods (id),
    CONSTRAINT fk_grading_configurations_scale FOREIGN KEY (grading_scale_id) REFERENCES grading_scales (id),
    CONSTRAINT uk_grading_configurations_teaching_period UNIQUE (teaching_period_id)
);
