CREATE TABLE grading_weights (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grading_configuration_id BIGINT       NOT NULL,
    evaluation_category_id   BIGINT       NOT NULL,
    weight                   NUMERIC(5, 2) NOT NULL,
    created_at               TIMESTAMP    NOT NULL,
    CONSTRAINT fk_grading_weights_configuration FOREIGN KEY (grading_configuration_id) REFERENCES grading_configurations (id),
    CONSTRAINT fk_grading_weights_category FOREIGN KEY (evaluation_category_id) REFERENCES evaluation_categories (id),
    CONSTRAINT uk_grading_weights UNIQUE (grading_configuration_id, evaluation_category_id)
);
