CREATE TABLE evaluations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id     BIGINT        NOT NULL,
    evaluation_category_id BIGINT        NOT NULL,
    name                   VARCHAR(150)  NOT NULL,
    description            TEXT,
    evaluation_date        TIMESTAMP,
    maximum_score          NUMERIC(6, 2) NOT NULL,
    created_at             TIMESTAMP     NOT NULL,
    updated_at             TIMESTAMP     NOT NULL,
    CONSTRAINT fk_evaluations_teaching_period FOREIGN KEY (teaching_period_id) REFERENCES teaching_periods (id),
    CONSTRAINT fk_evaluations_category FOREIGN KEY (evaluation_category_id) REFERENCES evaluation_categories (id)
);
