CREATE TABLE exams (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id       BIGINT    NOT NULL,
    number_of_questions INT       NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_exams_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_exams_evaluation UNIQUE (evaluation_id)
);
