CREATE TABLE exam_questions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id         BIGINT        NOT NULL,
    question_number INT           NOT NULL,
    statement       TEXT          NOT NULL,
    correct_option  VARCHAR(1)    NOT NULL,
    points          NUMERIC(6, 2) NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_exam_questions_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT uk_exam_questions UNIQUE (exam_id, question_number)
);
