CREATE TABLE exam_question_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT     NOT NULL,
    option_letter VARCHAR(1) NOT NULL,
    option_text   TEXT       NOT NULL,
    created_at    TIMESTAMP  NOT NULL,
    CONSTRAINT fk_exam_question_options_question FOREIGN KEY (question_id) REFERENCES exam_questions (id),
    CONSTRAINT uk_exam_question_options UNIQUE (question_id, option_letter)
);
