CREATE TABLE exam_submissions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id          BIGINT      NOT NULL,
    student_id       BIGINT      NOT NULL,
    student_code     VARCHAR(50) NOT NULL,
    detected_qr_data TEXT,
    image_path       VARCHAR(500),
    status           VARCHAR(30) NOT NULL,
    score            NUMERIC(6, 2),
    final_grade      NUMERIC(6, 2),
    submitted_at     TIMESTAMP,
    processed_at     TIMESTAMP,
    created_at       TIMESTAMP   NOT NULL,
    updated_at       TIMESTAMP   NOT NULL,
    CONSTRAINT fk_exam_submissions_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_submissions_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_exam_submissions UNIQUE (exam_id, student_id)
);
