CREATE TABLE exam_answers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id        BIGINT    NOT NULL,
    question_id          BIGINT    NOT NULL,
    selected_option      VARCHAR(1),
    is_correct           BOOLEAN,
    detection_confidence NUMERIC(5, 4),
    created_at           TIMESTAMP NOT NULL,
    CONSTRAINT fk_exam_answers_submission FOREIGN KEY (submission_id) REFERENCES exam_submissions (id),
    CONSTRAINT fk_exam_answers_question FOREIGN KEY (question_id) REFERENCES exam_questions (id),
    CONSTRAINT uk_exam_answers UNIQUE (submission_id, question_id)
);
