CREATE TABLE activities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT    NOT NULL,
    activity_type VARCHAR(50),
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_activities_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_activities_evaluation UNIQUE (evaluation_id)
);
