CREATE TABLE activity_grades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT        NOT NULL,
    student_id  BIGINT        NOT NULL,
    grade       NUMERIC(6, 2) NOT NULL,
    comment     VARCHAR(500),
    graded_at   TIMESTAMP,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_activity_grades_activity FOREIGN KEY (activity_id) REFERENCES activities (id),
    CONSTRAINT fk_activity_grades_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_activity_grades UNIQUE (activity_id, student_id)
);
