CREATE TABLE attendance_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT    NOT NULL,
    session_date  DATE      NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_attendance_sessions_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_attendance_sessions_evaluation UNIQUE (evaluation_id)
);
