CREATE TABLE attendance_records (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_session_id BIGINT      NOT NULL,
    student_id            BIGINT      NOT NULL,
    status                VARCHAR(30) NOT NULL,
    observation           VARCHAR(255),
    created_at            TIMESTAMP   NOT NULL,
    CONSTRAINT fk_attendance_records_session FOREIGN KEY (attendance_session_id) REFERENCES attendance_sessions (id),
    CONSTRAINT fk_attendance_records_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_attendance_records UNIQUE (attendance_session_id, student_id)
);
