CREATE TABLE import_batches (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    file_path         VARCHAR(500),
    status            VARCHAR(30)  NOT NULL,
    total_rows        INT,
    successful_rows   INT,
    failed_rows       INT,
    error_report_path VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL,
    completed_at      TIMESTAMP,
    CONSTRAINT fk_import_batches_user FOREIGN KEY (user_id) REFERENCES users (id)
);
