-- Fuera del DBML: requerida por el módulo Audit (quién, qué, cuándo, sobre qué entidad, resultado).
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    action      VARCHAR(50) NOT NULL,
    entity_type VARCHAR(100),
    entity_id   BIGINT,
    result      VARCHAR(20) NOT NULL,
    details     TEXT,
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_audit_logs_user_created ON audit_logs (user_id, created_at DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
