-- Estructura académica: grados, grupos, asignaturas, asignaciones docentes, periodos y horario de cada clase.
CREATE TABLE grades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uk_grades_name UNIQUE (name)
);

CREATE TABLE groups (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id      BIGINT      NOT NULL,
    name          VARCHAR(50) NOT NULL,
    academic_year INT         NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_groups_grade FOREIGN KEY (grade_id) REFERENCES grades (id),
    CONSTRAINT uk_groups_grade_name_year UNIQUE (grade_id, name, academic_year)
);

CREATE TABLE subjects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_subjects_name UNIQUE (name)
);

CREATE TABLE teaching_assignments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT    NOT NULL,
    group_id   BIGINT    NOT NULL,
    subject_id BIGINT    NOT NULL,
    active     BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_teaching_assignments_teacher FOREIGN KEY (teacher_id) REFERENCES users (id),
    CONSTRAINT fk_teaching_assignments_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_teaching_assignments_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
    CONSTRAINT uk_teaching_assignments UNIQUE (teacher_id, group_id, subject_id)
);
CREATE INDEX idx_teaching_assignments_group ON teaching_assignments (group_id);
CREATE INDEX idx_teaching_assignments_subject ON teaching_assignments (subject_id);

CREATE TABLE academic_periods (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);

CREATE TABLE teaching_periods (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_assignment_id BIGINT    NOT NULL,
    academic_period_id     BIGINT    NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    CONSTRAINT fk_teaching_periods_assignment FOREIGN KEY (teaching_assignment_id) REFERENCES teaching_assignments (id),
    CONSTRAINT fk_teaching_periods_period FOREIGN KEY (academic_period_id) REFERENCES academic_periods (id),
    CONSTRAINT uk_teaching_periods UNIQUE (teaching_assignment_id, academic_period_id)
);
CREATE INDEX idx_teaching_periods_period ON teaching_periods (academic_period_id);

-- Horario semanal de cada periodo de enseñanza (una fila por bloque de clase).
CREATE TABLE teaching_period_schedules (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id BIGINT      NOT NULL,
    day_of_week        VARCHAR(10) NOT NULL,
    start_time         TIME        NOT NULL,
    end_time           TIME        NOT NULL,
    room               VARCHAR(50),
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL,
    CONSTRAINT fk_teaching_period_schedules_tp FOREIGN KEY (teaching_period_id)
        REFERENCES teaching_periods (id) ON DELETE CASCADE,
    CONSTRAINT ck_teaching_period_schedules_times CHECK (end_time > start_time)
);
CREATE INDEX idx_teaching_period_schedules_tp ON teaching_period_schedules (teaching_period_id);
