CREATE TABLE exam_submission_batches (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id          BIGINT       NOT NULL,
    teacher_id       BIGINT       NOT NULL,
    file_name        VARCHAR(255),
    file_path        VARCHAR(500) NOT NULL,
    replace_existing BOOLEAN      NOT NULL,
    status           VARCHAR(30)  NOT NULL,
    status_detail    VARCHAR(500),
    total_pages      INT          NOT NULL,
    processed_pages  INT          NOT NULL,
    started_at       TIMESTAMP,
    completed_at     TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_exam_submission_batches_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_submission_batches_teacher FOREIGN KEY (teacher_id) REFERENCES users (id)
);

CREATE INDEX ix_exam_submission_batches_exam ON exam_submission_batches (exam_id);
CREATE INDEX ix_exam_submission_batches_status ON exam_submission_batches (status);

CREATE TABLE exam_submission_batch_pages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT      NOT NULL,
    page_number   INT         NOT NULL,
    outcome       VARCHAR(30) NOT NULL,
    error_code    VARCHAR(60),
    message       VARCHAR(500),
    student_code  VARCHAR(50),
    submission_id BIGINT,
    created_at    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_exam_submission_batch_pages_batch FOREIGN KEY (batch_id)
        REFERENCES exam_submission_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_submission_batch_pages_submission FOREIGN KEY (submission_id)
        REFERENCES exam_submissions (id) ON DELETE SET NULL,
    CONSTRAINT uk_exam_submission_batch_pages UNIQUE (batch_id, page_number)
);

CREATE INDEX ix_exam_submission_batch_pages_submission ON exam_submission_batch_pages (submission_id);
