-- Horario semanal de cada periodo de enseñanza (una fila por bloque de clase).
CREATE TABLE teaching_period_schedules (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id BIGINT      NOT NULL,
    day_of_week        VARCHAR(10) NOT NULL,
    start_time         TIME        NOT NULL,
    end_time           TIME        NOT NULL,
    room               VARCHAR(50),
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL,
    CONSTRAINT fk_teaching_period_schedules_tp FOREIGN KEY (teaching_period_id)
        REFERENCES teaching_periods (id) ON DELETE CASCADE,
    CONSTRAINT ck_teaching_period_schedules_times CHECK (end_time > start_time)
);

CREATE INDEX idx_teaching_period_schedules_tp ON teaching_period_schedules (teaching_period_id);
