-- Estudiantes (cada uno pertenece a un único profesor) y su matrícula en grupos del mismo profesor.
CREATE TABLE students (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id            BIGINT       NOT NULL,
    identification_number VARCHAR(50),
    student_code          VARCHAR(50)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(255),
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT fk_students_teacher FOREIGN KEY (teacher_id) REFERENCES users (id),
    CONSTRAINT uk_students_teacher_student_code UNIQUE (teacher_id, student_code),
    CONSTRAINT uk_students_teacher_identification_number UNIQUE (teacher_id, identification_number),
    CONSTRAINT uk_students_id_teacher UNIQUE (id, teacher_id)
);

-- Generación de student_code cuando el Excel de importación no lo trae.
CREATE SEQUENCE student_code_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE student_groups (
    student_id   BIGINT    NOT NULL,
    group_id     BIGINT    NOT NULL,
    teacher_id   BIGINT    NOT NULL,
    enrolled_at  TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP,
    active       BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_student_groups PRIMARY KEY (student_id, group_id),
    CONSTRAINT fk_student_groups_student FOREIGN KEY (student_id, teacher_id) REFERENCES students (id, teacher_id),
    CONSTRAINT fk_student_groups_group FOREIGN KEY (group_id, teacher_id) REFERENCES groups (id, teacher_id)
);
CREATE INDEX idx_student_groups_group ON student_groups (group_id);
