-- Estudiantes y su matrícula en grupos.
CREATE TABLE students (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification_number VARCHAR(50),
    student_code          VARCHAR(50)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(255),
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT uk_students_student_code UNIQUE (student_code),
    CONSTRAINT uk_students_identification_number UNIQUE (identification_number)
);

-- Generación de student_code cuando el Excel de importación no lo trae.
CREATE SEQUENCE student_code_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE student_groups (
    student_id   BIGINT    NOT NULL,
    group_id     BIGINT    NOT NULL,
    enrolled_at  TIMESTAMP NOT NULL,
    withdrawn_at TIMESTAMP,
    active       BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_student_groups PRIMARY KEY (student_id, group_id),
    CONSTRAINT fk_student_groups_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_student_groups_group FOREIGN KEY (group_id) REFERENCES groups (id)
);
CREATE INDEX idx_student_groups_group ON student_groups (group_id);
