-- Nota mínima para aprobar el periodo (opcional, dentro de la escala de la configuración).
ALTER TABLE grading_configurations ADD COLUMN passing_grade NUMERIC(6, 2);

-- Rúbrica de una evaluación (solo actividades): criterios cuyos pesos suman 100.
CREATE TABLE rubric_criteria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT        NOT NULL,
    position      INT           NOT NULL,
    name          VARCHAR(150)  NOT NULL,
    weight        NUMERIC(5, 2) NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_rubric_criteria_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id) ON DELETE CASCADE
);
CREATE INDEX idx_rubric_criteria_evaluation ON rubric_criteria (evaluation_id);

-- Puntaje de un estudiante en un criterio, sobre el puntaje máximo de la evaluación.
CREATE TABLE rubric_scores (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_id BIGINT        NOT NULL,
    student_id   BIGINT        NOT NULL,
    score        NUMERIC(6, 2) NOT NULL,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_rubric_scores_criterion FOREIGN KEY (criterion_id) REFERENCES rubric_criteria (id) ON DELETE CASCADE,
    CONSTRAINT fk_rubric_scores_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_rubric_scores UNIQUE (criterion_id, student_id)
);
CREATE INDEX idx_rubric_scores_student ON rubric_scores (student_id);

-- Archivo adjunto a la nota de un estudiante en una evaluación (uno por nota).
CREATE TABLE grade_attachments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT       NOT NULL,
    student_id    BIGINT       NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(150) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    storage_path  VARCHAR(500) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_grade_attachments_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id) ON DELETE CASCADE,
    CONSTRAINT fk_grade_attachments_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_grade_attachments UNIQUE (evaluation_id, student_id)
);
CREATE INDEX idx_grade_attachments_student ON grade_attachments (student_id);

-- Observación del docente sobre un estudiante en una clase (teaching period).
CREATE TABLE student_observations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id BIGINT        NOT NULL,
    student_id         BIGINT        NOT NULL,
    text               VARCHAR(1000) NOT NULL,
    created_at         TIMESTAMP     NOT NULL,
    updated_at         TIMESTAMP     NOT NULL,
    CONSTRAINT fk_student_observations_teaching_period FOREIGN KEY (teaching_period_id) REFERENCES teaching_periods (id) ON DELETE CASCADE,
    CONSTRAINT fk_student_observations_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_student_observations UNIQUE (teaching_period_id, student_id)
);
CREATE INDEX idx_student_observations_student ON student_observations (student_id);
