CREATE TABLE grades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uk_grades_name UNIQUE (name)
);
