-- Calificación: escalas, categorías de evaluación y configuración/pesos por periodo de enseñanza.
-- teacher_id NULL = escala del sistema (solo lectura, visible para todos); si no, es privada de ese profesor.
CREATE TABLE grading_scales (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id    BIGINT,
    name          VARCHAR(100)  NOT NULL,
    minimum_value NUMERIC(6, 2) NOT NULL,
    maximum_value NUMERIC(6, 2) NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_grading_scales_teacher FOREIGN KEY (teacher_id) REFERENCES users (id)
);
CREATE INDEX idx_grading_scales_teacher ON grading_scales (teacher_id);

CREATE TABLE evaluation_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_evaluation_categories_name UNIQUE (name)
);

CREATE TABLE grading_configurations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teaching_period_id BIGINT        NOT NULL,
    grading_scale_id   BIGINT        NOT NULL,
    created_at         TIMESTAMP     NOT NULL,
    updated_at         TIMESTAMP     NOT NULL,
    -- Nota mínima para aprobar el periodo (opcional, dentro de la escala de la configuración).
    passing_grade      NUMERIC(6, 2),
    CONSTRAINT fk_grading_configurations_teaching_period FOREIGN KEY (teaching_period_id) REFERENCES teaching_periods (id),
    CONSTRAINT fk_grading_configurations_scale FOREIGN KEY (grading_scale_id) REFERENCES grading_scales (id),
    CONSTRAINT uk_grading_configurations_teaching_period UNIQUE (teaching_period_id)
);
CREATE INDEX idx_grading_configurations_scale ON grading_configurations (grading_scale_id);

CREATE TABLE grading_weights (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grading_configuration_id BIGINT        NOT NULL,
    evaluation_category_id   BIGINT        NOT NULL,
    weight                   NUMERIC(5, 2) NOT NULL,
    created_at               TIMESTAMP     NOT NULL,
    CONSTRAINT fk_grading_weights_configuration FOREIGN KEY (grading_configuration_id) REFERENCES grading_configurations (id),
    CONSTRAINT fk_grading_weights_category FOREIGN KEY (evaluation_category_id) REFERENCES evaluation_categories (id),
    CONSTRAINT uk_grading_weights UNIQUE (grading_configuration_id, evaluation_category_id)
);
