CREATE TABLE groups (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id      BIGINT      NOT NULL,
    name          VARCHAR(50) NOT NULL,
    academic_year INT         NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_groups_grade FOREIGN KEY (grade_id) REFERENCES grades (id),
    CONSTRAINT uk_groups_grade_name_year UNIQUE (grade_id, name, academic_year)
);
