-- Exámenes de selección múltiple: preguntas, entregas (hojas de respuesta OMR) y lotes de PDF escaneados.
CREATE TABLE exams (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id       BIGINT    NOT NULL,
    number_of_questions INT       NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    CONSTRAINT fk_exams_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_exams_evaluation UNIQUE (evaluation_id)
);

CREATE TABLE exam_questions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id         BIGINT        NOT NULL,
    question_number INT           NOT NULL,
    statement       TEXT          NOT NULL,
    correct_option  VARCHAR(1)    NOT NULL,
    points          NUMERIC(6, 2) NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_exam_questions_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT uk_exam_questions UNIQUE (exam_id, question_number)
);

CREATE TABLE exam_question_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT     NOT NULL,
    option_letter VARCHAR(1) NOT NULL,
    option_text   TEXT       NOT NULL,
    created_at    TIMESTAMP  NOT NULL,
    CONSTRAINT fk_exam_question_options_question FOREIGN KEY (question_id) REFERENCES exam_questions (id),
    CONSTRAINT uk_exam_question_options UNIQUE (question_id, option_letter)
);

CREATE TABLE exam_submissions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id          BIGINT       NOT NULL,
    student_id       BIGINT       NOT NULL,
    student_code     VARCHAR(50)  NOT NULL,
    detected_qr_data TEXT,
    image_path       VARCHAR(500),
    status           VARCHAR(30)  NOT NULL,
    score            NUMERIC(6, 2),
    final_grade      NUMERIC(6, 2),
    submitted_at     TIMESTAMP,
    processed_at     TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    -- Motivo legible del estado (FAILED / REVIEW_REQUIRED).
    status_detail    VARCHAR(500),
    CONSTRAINT fk_exam_submissions_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_submissions_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_exam_submissions UNIQUE (exam_id, student_id)
);
CREATE INDEX idx_exam_submissions_student ON exam_submissions (student_id);

CREATE TABLE exam_answers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id        BIGINT        NOT NULL,
    question_id          BIGINT        NOT NULL,
    selected_option      VARCHAR(1),
    is_correct           BOOLEAN,
    detection_confidence NUMERIC(5, 4),
    created_at           TIMESTAMP     NOT NULL,
    -- MARKED / EMPTY / MULTIPLE_MARK / REVIEW_REQUIRED / MANUAL.
    detection_status     VARCHAR(20)   NOT NULL,
    CONSTRAINT fk_exam_answers_submission FOREIGN KEY (submission_id) REFERENCES exam_submissions (id),
    CONSTRAINT fk_exam_answers_question FOREIGN KEY (question_id) REFERENCES exam_questions (id),
    CONSTRAINT uk_exam_answers UNIQUE (submission_id, question_id)
);
CREATE INDEX idx_exam_answers_question ON exam_answers (question_id);

-- Lote de un PDF con hojas escaneadas, procesado en segundo plano.
-- El PDF original se borra tras el periodo de retención (file_path = NULL, file_purged_at); el lote y sus resultados se conservan.
CREATE TABLE exam_submission_batches (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id          BIGINT       NOT NULL,
    teacher_id       BIGINT       NOT NULL,
    file_name        VARCHAR(255),
    file_path        VARCHAR(500),
    replace_existing BOOLEAN      NOT NULL,
    status           VARCHAR(30)  NOT NULL,
    status_detail    VARCHAR(500),
    total_pages      INT          NOT NULL,
    processed_pages  INT          NOT NULL,
    started_at       TIMESTAMP,
    completed_at     TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    file_purged_at   TIMESTAMP,
    CONSTRAINT fk_exam_submission_batches_exam FOREIGN KEY (exam_id) REFERENCES exams (id),
    CONSTRAINT fk_exam_submission_batches_teacher FOREIGN KEY (teacher_id) REFERENCES users (id)
);
CREATE INDEX ix_exam_submission_batches_exam ON exam_submission_batches (exam_id);
CREATE INDEX ix_exam_submission_batches_status ON exam_submission_batches (status);

CREATE TABLE exam_submission_batch_pages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT      NOT NULL,
    page_number   INT         NOT NULL,
    outcome       VARCHAR(30) NOT NULL,
    error_code    VARCHAR(60),
    message       VARCHAR(500),
    student_code  VARCHAR(50),
    submission_id BIGINT,
    created_at    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_exam_submission_batch_pages_batch FOREIGN KEY (batch_id)
        REFERENCES exam_submission_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_submission_batch_pages_submission FOREIGN KEY (submission_id)
        REFERENCES exam_submissions (id) ON DELETE SET NULL,
    CONSTRAINT uk_exam_submission_batch_pages UNIQUE (batch_id, page_number)
);
CREATE INDEX ix_exam_submission_batch_pages_submission ON exam_submission_batch_pages (submission_id);
