CREATE TABLE students (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification_number VARCHAR(50),
    student_code          VARCHAR(50)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(255),
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT uk_students_student_code UNIQUE (student_code),
    CONSTRAINT uk_students_identification_number UNIQUE (identification_number)
);
