-- Actividades calificadas manualmente y asistencia.
CREATE TABLE activities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT    NOT NULL,
    activity_type VARCHAR(50),
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_activities_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_activities_evaluation UNIQUE (evaluation_id)
);

CREATE TABLE activity_grades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT        NOT NULL,
    student_id  BIGINT        NOT NULL,
    grade       NUMERIC(6, 2) NOT NULL,
    comment     VARCHAR(500),
    graded_at   TIMESTAMP,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_activity_grades_activity FOREIGN KEY (activity_id) REFERENCES activities (id),
    CONSTRAINT fk_activity_grades_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_activity_grades UNIQUE (activity_id, student_id)
);
CREATE INDEX idx_activity_grades_student ON activity_grades (student_id);

CREATE TABLE attendance_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT    NOT NULL,
    session_date  DATE      NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_attendance_sessions_evaluation FOREIGN KEY (evaluation_id) REFERENCES evaluations (id),
    CONSTRAINT uk_attendance_sessions_evaluation UNIQUE (evaluation_id)
);

CREATE TABLE attendance_records (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_session_id BIGINT      NOT NULL,
    student_id            BIGINT      NOT NULL,
    status                VARCHAR(30) NOT NULL,
    observation           VARCHAR(255),
    created_at            TIMESTAMP   NOT NULL,
    CONSTRAINT fk_attendance_records_session FOREIGN KEY (attendance_session_id) REFERENCES attendance_sessions (id),
    CONSTRAINT fk_attendance_records_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT uk_attendance_records UNIQUE (attendance_session_id, student_id)
);
CREATE INDEX idx_attendance_records_student ON attendance_records (student_id);
