-- Importaciones de Excel y auditoría.
CREATE TABLE import_batches (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    file_path         VARCHAR(500),
    status            VARCHAR(30)  NOT NULL,
    total_rows        INT,
    successful_rows   INT,
    failed_rows       INT,
    error_report_path VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL,
    completed_at      TIMESTAMP,
    CONSTRAINT fk_import_batches_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_import_batches_user ON import_batches (user_id, created_at DESC);

-- Quién, qué, cuándo, sobre qué entidad y con qué resultado. teaching_period_id liga el registro a su clase
-- (actividad reciente) y entity_label guarda un nombre legible de la entidad.
-- Sin FK a teaching_periods: la auditoría debe sobrevivir al borrado del periodo de enseñanza.
CREATE TABLE audit_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT,
    action             VARCHAR(50)  NOT NULL,
    entity_type        VARCHAR(100),
    entity_id          BIGINT,
    result             VARCHAR(20)  NOT NULL,
    details            TEXT,
    created_at         TIMESTAMP    NOT NULL,
    teaching_period_id BIGINT,
    entity_label       VARCHAR(255),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_audit_logs_user_created ON audit_logs (user_id, created_at DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_teaching_period_created ON audit_logs (teaching_period_id, created_at DESC);
