CREATE TABLE teaching_assignments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT    NOT NULL,
    group_id   BIGINT    NOT NULL,
    subject_id BIGINT    NOT NULL,
    active     BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_teaching_assignments_teacher FOREIGN KEY (teacher_id) REFERENCES users (id),
    CONSTRAINT fk_teaching_assignments_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_teaching_assignments_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
    CONSTRAINT uk_teaching_assignments UNIQUE (teacher_id, group_id, subject_id)
);
